In [2]:
#Import all needed dependencies and libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import gmaps
import os

# Import API key
from g_keys import keys
print(keys)

AIzaSyDVgKYUR5aQocXmC6uiPZH6q3-5aqVSp9Y

In [3]:
#Specifies the file path for the csv data
csv_file = os.path.join('..', 'WeatherPy', 'output_data', 'city_weather.csv')

city_df = pd.read_csv(csv_file)
city_df

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed
0,3840300,Presidencia Roque Sáenz Peña,AR,-26.7852,-60.4388,63.57,11,1,13.33
1,5848280,Kapaa,US,22.0752,-159.3190,75.11,81,40,13.80
2,2021188,Kurumkan,RU,54.3000,110.3000,65.97,53,59,4.52
3,5866583,Saint Paul Harbor,US,57.7900,-152.4072,54.91,76,1,4.61
4,5746545,Portland,US,45.5234,-122.6762,69.10,71,75,1.01
...,...,...,...,...,...,...,...,...,...
533,8079926,Labuhan,ID,-6.8844,112.2051,73.78,85,44,7.07
534,898905,Sesheke,ZM,-17.4759,24.2968,60.98,35,0,5.41
535,5044290,Saint Anthony,US,45.0205,-93.2180,87.08,59,1,4.00
536,4031742,Egvekinot,RU,66.3167,-179.1667,43.84,92,100,8.46
537,3837213,San Juan,AR,-31.5375,-68.5364,52.52,32,0,7.43

In [4]:
#Setting up the configurations for the format of the gmaps object
gmaps.configure(api_key=keys)
locations = city_df[["Lat", "Lng"]]
humidity = city_df["Humidity"]

fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False)
heat_layer.max_intensity = 100
heat_layer.point_radius = 5
fig.add_layer(heat_layer)

In [5]:
#Set ideal df params to only include the cities with ideal weather...
best_weather_df = city_df[(city_df['Temperature'] >= 75) & (city_df['Temperature'] <= 80)]
best_weather_df = best_weather_df[best_weather_df['Wind Speed'] <= 10]
best_weather_df = best_weather_df[best_weather_df['Clouds'] <= 10]
best_weather_df = best_weather_df[best_weather_df['Humidity'] <= 70]
hotel_df_response = best_weather_df
hotel_df_response

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed
65,5850554,Makakilo City,US,21.3469,-158.0858,76.78,65,1,4.61
112,3470744,Barra da Estiva,BR,-13.6261,-41.3269,78.87,34,9,8.46
159,3976161,Adolfo López Mateos,MX,28.4667,-107.3000,77.94,34,3,8.28
282,5364271,Laguna,US,38.4210,-121.4238,76.87,35,1,1.99
402,6127749,Rosetown,CA,51.5501,-108.0014,78.78,44,6,6.91

In [6]:
#Saving hotel names under a new column in our hotel_df_response df...
hotel_df_response['Hotel Name'] = ""
hotel_df_response
#Loop checks for the coordinates of hotels within 5000 ft of our listed cities
for index, row in hotel_df_response.iterrows():
    try:
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        params = {
        "keyword": "hotel",
        "radius": 5000,
        "key": keys,
        }
        lat = row['Lat']
        lng = row['Lng']
        params['location'] = f"{lat}, {lng}"
        hotel_data = requests.get(base_url, params=params).json()
        hotel_df_response.loc[index, "Hotel Name"] = hotel_data["results"][0]["name"]
    except IndexError:
        hotel_df_response.loc[index, "Hotel Name"] = "NaN"
hotel_df_response

,City ID,City,Country,Lat,Lng,Temperature,Humidity,Clouds,Wind Speed,Hotel Name
65,5850554,Makakilo City,US,21.3469,-158.0858,76.78,65,1,4.61,Hampton Inn & Suites Oahu/Kapolei
112,3470744,Barra da Estiva,BR,-13.6261,-41.3269,78.87,34,9,8.46,Hotel Santa Rita
159,3976161,Adolfo López Mateos,MX,28.4667,-107.3000,77.94,34,3,8.28,Hotel Viajero
282,5364271,Laguna,US,38.4210,-121.4238,76.87,35,1,1.99,Hampton Inn & Suites Sacramento-Elk Grove Lagu...
402,6127749,Rosetown,CA,51.5501,-108.0014,78.78,44,6,6.91,Travelodge by Wyndham Rosetown

In [7]:
#Adds hotel markers to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""


# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df_response.iterrows()]
locations = hotel_df_response[["Lat", "Lng"]]

In [8]:
#Specifying the markers to be used on the gmaps figure...
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))